package cli

import (
	"os"
	"path/filepath"
	"strings"
)

const slashCommandName = "better-review"

// Managed files carry this marker; a user who removes it owns the file and
// tx init will never overwrite it again.
const slashCommandMarker = "<!-- generated by tx init; remove this line to keep local edits -->"

// Body for agents that substitute $ARGUMENTS (Claude Code, Codex).
const slashCommandBodyArgs = slashCommandMarker + `

Run an AI code review of the current change with Totality.

Use the ` + "`tx_review`" + ` MCP tool if it is available, passing "$ARGUMENTS" as the
` + "`prompt`" + ` parameter (omit the parameter when it is empty). If the MCP tool is
unavailable, run the CLI instead: ` + "`" + `tx review "$ARGUMENTS"` + "`" + ` (plain
` + "`tx review`" + ` when there is no prompt).

Report the findings. Do not change any code unless the user asks.
`

// Body for Cursor, which appends the user's text after the command instead of
// substituting a placeholder.
const slashCommandBodyPlain = slashCommandMarker + `

Run an AI code review of the current change with Totality.

Use the ` + "`tx_review`" + ` MCP tool if it is available. If the user added
instructions after the command, pass them as the ` + "`prompt`" + ` parameter. If the
MCP tool is unavailable, run the ` + "`tx review`" + ` CLI instead, quoting those
instructions as the positional prompt argument.

Report the findings. Do not change any code unless the user asks.
`

const slashCommandClaudeFrontmatter = `---
description: Totality AI review of the current change
argument-hint: [optional reviewer prompt]
---

`

type slashCommandTarget struct {
	name    string   // display name, e.g. "Claude Code"
	gateDir string   // directory under $HOME whose presence means the agent is installed
	relPath []string // command file path under $HOME
	content string
}

func slashCommandTargets() []slashCommandTarget {
	file := slashCommandName + ".md"
	return []slashCommandTarget{
		{
			name:    "Claude Code",
			gateDir: ".claude",
			relPath: []string{".claude", "commands", file},
			content: slashCommandClaudeFrontmatter + slashCommandBodyArgs,
		},
		{
			name:    "Cursor",
			gateDir: ".cursor",
			relPath: []string{".cursor", "commands", file},
			content: slashCommandBodyPlain,
		},
		{
			name:    "Codex",
			gateDir: ".codex",
			relPath: []string{".codex", "prompts", file},
			content: slashCommandBodyArgs,
		},
	}
}

// installSlashCommands writes the user-level /better-review command file for
// each agent whose config directory exists, skipping files the user has taken
// ownership of. It returns the display names of agents whose command file is
// in place after the call.
func installSlashCommands() ([]string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, err
	}
	var installed []string
	for _, target := range slashCommandTargets() {
		if info, statErr := os.Stat(filepath.Join(home, target.gateDir)); statErr != nil || !info.IsDir() {
			continue
		}
		path := filepath.Join(append([]string{home}, target.relPath...)...)
		if data, readErr := os.ReadFile(path); readErr == nil {
			if !strings.Contains(string(data), slashCommandMarker) {
				continue
			}
			if string(data) == target.content {
				installed = append(installed, target.name)
				continue
			}
		}
		if mkErr := os.MkdirAll(filepath.Dir(path), 0o755); mkErr != nil {
			continue
		}
		if writeErr := os.WriteFile(path, []byte(target.content), 0o644); writeErr != nil {
			continue
		}
		installed = append(installed, target.name)
	}
	return installed, nil
}
