package cli

import (
	"os"
	"path/filepath"
	"strings"
)

// Managed files carry this marker; a user who removes it owns the file and
// gx init will never overwrite it again.
const slashCommandMarker = "<!-- generated by gx init; remove this line to keep local edits -->"

// slashCommand is one command gx init installs into every detected agent. Each
// command carries its own content in the two body dialects the agents speak,
// and its own legacy names: files this tool installed under earlier names are
// removed on the next init so a rename leaves one command rather than two, and
// only when the file still carries a marker this tool wrote — a file the user
// has taken ownership of is theirs to delete.
type slashCommand struct {
	name         string // slash name and file base name, e.g. "gx" -> gx.md
	description  string // Claude Code frontmatter description
	argumentHint string // Claude Code frontmatter argument-hint
	bodyArgs     string // body for agents that substitute $ARGUMENTS (Claude Code, Codex)
	bodyPlain    string // body for Cursor, which appends the user's text instead
	legacyNames  []string
}

func slashCommands() []slashCommand {
	return []slashCommand{
		{
			name:         "gx",
			description:  "gx AI review of the current change",
			argumentHint: "[optional reviewer prompt]",
			bodyArgs:     slashGxBodyArgs,
			bodyPlain:    slashGxBodyPlain,
			legacyNames:  []string{"better-review"},
		},
		{
			name:         "constraints",
			description:  "gx pre-ship constraints exit gate for the current change",
			argumentHint: "[optional focus or intent hint]",
			bodyArgs:     slashConstraintsBodyArgs,
			bodyPlain:    slashConstraintsBodyPlain,
		},
	}
}

// Body for agents that substitute $ARGUMENTS (Claude Code, Codex).
const slashGxBodyArgs = slashCommandMarker + `

Run an AI code review of the current change with gx.

Use the ` + "`gx_review`" + ` MCP tool if it is available, passing "$ARGUMENTS" as the
` + "`prompt`" + ` parameter (omit the parameter when it is empty) and ` + "`fast: true`" + `.
If the MCP tool is unavailable, run the CLI instead:
` + "`" + `GX_CLIENT=slash-gx gx review --fast "$ARGUMENTS"` + "`" + ` (plain
` + "`GX_CLIENT=slash-gx gx review --fast`" + ` when there is no prompt). Keep the
` + "`GX_CLIENT=slash-gx`" + ` prefix — it labels the run as a /gx invocation.

` + "`--fast`" + ` is right for an interactive review: it uses one reviewer instead of
two, skips the verification pass and the project's test suite, and writes
findings without code examples. If the user asks for the most thorough review,
or wants the result posted to a pull request, drop ` + "`--fast`" + `.

Report the findings. Do not change any code unless the user asks.
`

// Body for Cursor, which appends the user's text after the command instead of
// substituting a placeholder.
const slashGxBodyPlain = slashCommandMarker + `

Run an AI code review of the current change with gx.

Use the ` + "`gx_review`" + ` MCP tool if it is available, with ` + "`fast: true`" + `. If the
user added instructions after the command, pass them as the ` + "`prompt`" + `
parameter. If the MCP tool is unavailable, run
` + "`GX_CLIENT=slash-gx gx review --fast`" + ` instead, quoting those instructions as
the positional prompt argument. Keep the ` + "`GX_CLIENT=slash-gx`" + ` prefix — it
labels the run as a /gx invocation.

` + "`--fast`" + ` is right for an interactive review: it uses one reviewer instead of
two, skips the verification pass and the project's test suite, and writes
findings without code examples. If the user asks for the most thorough review,
or wants the result posted to a pull request, drop ` + "`--fast`" + `.

Report the findings. Do not change any code unless the user asks.
`

// The /constraints bodies must never contain a "---" line: the Codex file is
// the args body verbatim, and a test pins that it carries no frontmatter.
const slashConstraintsBodyArgs = slashCommandMarker + `

Run the gx constraints exit gate on the current change.

Use the ` + "`gx_constraints`" + ` MCP tool if it is available, passing "$ARGUMENTS" as
the ` + "`prompt`" + ` parameter (omit the parameter when it is empty). If the MCP tool
is unavailable, run the CLI instead:
` + "`" + `GX_CLIENT=slash-constraints gx constraints --md --report-only "$ARGUMENTS"` + "`" + `
(plain ` + "`GX_CLIENT=slash-constraints gx constraints --md --report-only`" + ` when
there is no hint). Keep the ` + "`GX_CLIENT=slash-constraints`" + ` prefix — it labels
the run as a /constraints invocation.

The gate checks the change against six constraints — correctness, security,
code health, back-pressure, accessibility, performance — reporting PASS, FAIL,
or SKIPPED for each plus a ship / no-ship verdict. Deterministic checks (the
project's tests and linters, a secrets scan, dependency audits) decide what
they can; one AI judgment call covers the rest. Pass ` + "`verbose: true`" + ` (or
` + "`--verbose`" + `) when you want the per-gate source files.

Relay the full per-gate report. If any gate FAILED, suggest a concrete fix for
each failed gate, but do not change any code unless the user asks. If every
gate passed or was skipped, tell the user the change is clear to ship and ask
whether to continue.
`

const slashConstraintsBodyPlain = slashCommandMarker + `

Run the gx constraints exit gate on the current change.

Use the ` + "`gx_constraints`" + ` MCP tool if it is available. If the user added
instructions after the command, pass them as the ` + "`prompt`" + ` parameter. If the
MCP tool is unavailable, run
` + "`GX_CLIENT=slash-constraints gx constraints --md --report-only`" + ` instead,
quoting those instructions as the positional hint argument. Keep the
` + "`GX_CLIENT=slash-constraints`" + ` prefix — it labels the run as a /constraints
invocation.

The gate checks the change against six constraints — correctness, security,
code health, back-pressure, accessibility, performance — reporting PASS, FAIL,
or SKIPPED for each plus a ship / no-ship verdict. Deterministic checks (the
project's tests and linters, a secrets scan, dependency audits) decide what
they can; one AI judgment call covers the rest. Pass ` + "`--verbose`" + ` when you
want the per-gate source files.

Relay the full per-gate report. If any gate FAILED, suggest a concrete fix for
each failed gate, but do not change any code unless the user asks. If every
gate passed or was skipped, tell the user the change is clear to ship and ask
whether to continue.
`

// slashCommandAgent is one coding agent gx can install commands into: where
// its command files live under $HOME, and how a command renders for it.
type slashCommandAgent struct {
	name    string   // display name, e.g. "Claude Code"
	gateDir string   // directory under $HOME whose presence means the agent is installed
	dir     []string // command directory under $HOME
	render  func(slashCommand) string
}

func slashCommandAgents() []slashCommandAgent {
	return []slashCommandAgent{
		{
			name:    "Claude Code",
			gateDir: ".claude",
			dir:     []string{".claude", "commands"},
			render:  renderClaudeSlashCommand,
		},
		{
			name:    "Cursor",
			gateDir: ".cursor",
			dir:     []string{".cursor", "commands"},
			render:  func(cmd slashCommand) string { return cmd.bodyPlain },
		},
		{
			name:    "Codex",
			gateDir: ".codex",
			dir:     []string{".codex", "prompts"},
			render:  func(cmd slashCommand) string { return cmd.bodyArgs },
		},
	}
}

func renderClaudeSlashCommand(cmd slashCommand) string {
	return "---\ndescription: " + cmd.description + "\nargument-hint: " + cmd.argumentHint + "\n---\n\n" + cmd.bodyArgs
}

// installSlashCommands writes the user-level command files for each agent
// whose config directory exists, skipping files the user has taken ownership
// of and removing files left behind under earlier command names. It returns
// the display names of agents with at least one managed command file in place
// after the call — with several commands per agent, per-command precision
// would say more than the one init output line can show, and write errors are
// already swallowed file by file in the same spirit.
func installSlashCommands() ([]string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, err
	}
	var installed []string
	for _, agent := range slashCommandAgents() {
		if info, statErr := os.Stat(filepath.Join(home, agent.gateDir)); statErr != nil || !info.IsDir() {
			continue
		}
		inPlace := false
		for _, cmd := range slashCommands() {
			removeLegacySlashCommands(home, agent, cmd)
			path := filepath.Join(append(append([]string{home}, agent.dir...), cmd.name+".md")...)
			content := agent.render(cmd)
			if data, readErr := os.ReadFile(path); readErr == nil {
				if !isManagedSlashCommand(string(data)) {
					// User-owned; leave this file alone, keep installing the rest.
					continue
				}
				if string(data) == content {
					inPlace = true
					continue
				}
			}
			if mkErr := os.MkdirAll(filepath.Dir(path), 0o755); mkErr != nil {
				continue
			}
			if writeErr := os.WriteFile(path, []byte(content), 0o644); writeErr != nil {
				continue
			}
			inPlace = true
		}
		if inPlace {
			installed = append(installed, agent.name)
		}
	}
	return installed, nil
}

// isManagedSlashCommand reports whether this tool wrote the file.
func isManagedSlashCommand(content string) bool {
	return strings.Contains(content, slashCommandMarker)
}

// removeLegacySlashCommands deletes command files this tool installed under a
// previous name, leaving anything the user has edited in place. A legacy name
// that collides with any CURRENT command's name is never deleted: all commands
// share one directory per agent, so deleting it would delete a live command.
func removeLegacySlashCommands(home string, agent slashCommandAgent, cmd slashCommand) {
	for _, legacy := range cmd.legacyNames {
		if slashCommandNameInUse(legacy) {
			continue
		}
		path := filepath.Join(append(append([]string{home}, agent.dir...), legacy+".md")...)
		data, err := os.ReadFile(path)
		if err != nil || !isManagedSlashCommand(string(data)) {
			continue
		}
		_ = os.Remove(path)
	}
}

func slashCommandNameInUse(name string) bool {
	for _, cmd := range slashCommands() {
		if cmd.name == name {
			return true
		}
	}
	return false
}
