package cli

import (
	"os"
	"path/filepath"
	"strings"
)

const slashCommandName = "gx"

// Managed files carry this marker; a user who removes it owns the file and
// gx init will never overwrite it again.
const slashCommandMarker = "<!-- generated by gx init; remove this line to keep local edits -->"

// legacySlashCommandNames are command files this tool installed under earlier
// names. They are removed on the next init so a rename leaves one command
// rather than two, and only when the file still carries a marker this tool
// wrote — a file the user has taken ownership of is theirs to delete.
var legacySlashCommandNames = []string{"better-review"}

// Body for agents that substitute $ARGUMENTS (Claude Code, Codex).
const slashCommandBodyArgs = slashCommandMarker + `

Run an AI code review of the current change with gx.

Use the ` + "`gx_review`" + ` MCP tool if it is available, passing "$ARGUMENTS" as the
` + "`prompt`" + ` parameter (omit the parameter when it is empty) and ` + "`fast: true`" + `.
If the MCP tool is unavailable, run the CLI instead:
` + "`" + `gx review --fast "$ARGUMENTS"` + "`" + ` (plain ` + "`gx review --fast`" + ` when there is
no prompt).

` + "`--fast`" + ` is right for an interactive review: it uses one reviewer instead of
two, skips the verification pass and the project's test suite, and writes
findings without code examples. If the user asks for the most thorough review,
or wants the result posted to a pull request, drop ` + "`--fast`" + `.

Report the findings. Do not change any code unless the user asks.
`

// Body for Cursor, which appends the user's text after the command instead of
// substituting a placeholder.
const slashCommandBodyPlain = slashCommandMarker + `

Run an AI code review of the current change with gx.

Use the ` + "`gx_review`" + ` MCP tool if it is available, with ` + "`fast: true`" + `. If the
user added instructions after the command, pass them as the ` + "`prompt`" + `
parameter. If the MCP tool is unavailable, run ` + "`gx review --fast`" + ` instead,
quoting those instructions as the positional prompt argument.

` + "`--fast`" + ` is right for an interactive review: it uses one reviewer instead of
two, skips the verification pass and the project's test suite, and writes
findings without code examples. If the user asks for the most thorough review,
or wants the result posted to a pull request, drop ` + "`--fast`" + `.

Report the findings. Do not change any code unless the user asks.
`

const slashCommandClaudeFrontmatter = `---
description: gx AI review of the current change
argument-hint: [optional reviewer prompt]
---

`

type slashCommandTarget struct {
	name    string   // display name, e.g. "Claude Code"
	gateDir string   // directory under $HOME whose presence means the agent is installed
	relPath []string // command file path under $HOME
	content string
}

func slashCommandTargets() []slashCommandTarget {
	file := slashCommandName + ".md"
	return []slashCommandTarget{
		{
			name:    "Claude Code",
			gateDir: ".claude",
			relPath: []string{".claude", "commands", file},
			content: slashCommandClaudeFrontmatter + slashCommandBodyArgs,
		},
		{
			name:    "Cursor",
			gateDir: ".cursor",
			relPath: []string{".cursor", "commands", file},
			content: slashCommandBodyPlain,
		},
		{
			name:    "Codex",
			gateDir: ".codex",
			relPath: []string{".codex", "prompts", file},
			content: slashCommandBodyArgs,
		},
	}
}

// installSlashCommands writes the user-level /gx command file for each agent
// whose config directory exists, skipping files the user has taken ownership
// of and removing files left behind under earlier command names. It returns the
// display names of agents whose command file is in place after the call.
func installSlashCommands() ([]string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, err
	}
	var installed []string
	for _, target := range slashCommandTargets() {
		if info, statErr := os.Stat(filepath.Join(home, target.gateDir)); statErr != nil || !info.IsDir() {
			continue
		}
		path := filepath.Join(append([]string{home}, target.relPath...)...)
		removeLegacySlashCommands(home, target)
		if data, readErr := os.ReadFile(path); readErr == nil {
			if !isManagedSlashCommand(string(data)) {
				continue
			}
			if string(data) == target.content {
				installed = append(installed, target.name)
				continue
			}
		}
		if mkErr := os.MkdirAll(filepath.Dir(path), 0o755); mkErr != nil {
			continue
		}
		if writeErr := os.WriteFile(path, []byte(target.content), 0o644); writeErr != nil {
			continue
		}
		installed = append(installed, target.name)
	}
	return installed, nil
}

// isManagedSlashCommand reports whether this tool wrote the file.
func isManagedSlashCommand(content string) bool {
	return strings.Contains(content, slashCommandMarker)
}

// removeLegacySlashCommands deletes command files this tool installed under a
// previous name, leaving anything the user has edited in place.
func removeLegacySlashCommands(home string, target slashCommandTarget) {
	if len(target.relPath) == 0 {
		return
	}
	for _, legacy := range legacySlashCommandNames {
		if legacy == slashCommandName {
			continue
		}
		parts := append([]string(nil), target.relPath...)
		parts[len(parts)-1] = legacy + ".md"
		path := filepath.Join(append([]string{home}, parts...)...)
		data, err := os.ReadFile(path)
		if err != nil || !isManagedSlashCommand(string(data)) {
			continue
		}
		_ = os.Remove(path)
	}
}
